---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "frontend-config"
  labels:
    app.kubernetes.io/name: "my-aspire-app"
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.frontend.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.frontend.port_http }}"
  API_HTTP: "http://api-service:{{ .Values.parameters.api.port_http }}"
  services__api__http__0: "http://api-service:{{ .Values.parameters.api.port_http }}"
  API_HTTPS: "https://api-service:{{ .Values.parameters.api.port_http }}"
  services__api__https__0: "https://api-service:{{ .Values.parameters.api.port_http }}"
