---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "ratingservice-secrets"
  labels:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "ratingservice"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.ratingservice.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.ratingservice.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.ratingservice.cache_password }}@cache-service:6379"
type: "Opaque"
