---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "migration-deployment"
  labels:
    app.kubernetes.io/name: "my-aspire-app"
    app.kubernetes.io/component: "migration"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "my-aspire-app"
        app.kubernetes.io/component: "migration"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "{{ .Values.parameters.migration.migration_image }}"
          name: "migration"
          envFrom:
            - configMapRef:
                name: "migration-config"
            - secretRef:
                name: "migration-secrets"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "my-aspire-app"
      app.kubernetes.io/component: "migration"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
