---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "api-secrets"
  labels:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__podcasts: "Server=server-service,1433;User ID=sa;Password={{ .Values.secrets.api.password }};TrustServerCertificate=true;Initial Catalog=podcasts"
  PODCASTS_PASSWORD: "{{ .Values.secrets.api.password }}"
  PODCASTS_URI: "mssql://sa:{{ .Values.secrets.api.password }}@server-service:1433/podcasts"
type: "Opaque"
