---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "server-secrets"
  labels:
    app.kubernetes.io/name: "my-aspire-app"
    app.kubernetes.io/component: "server"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  MSSQL_SA_PASSWORD: "{{ .Values.secrets.server.password }}"
type: "Opaque"
